/**
 * Agent — Orchestrator
 *
 * The core loop: receives a message, assembles context, calls Claude,
 * parses memory intents and task intents, returns the clean reply.
 */

import type { Config } from "../config/index.ts";
import type { MemorySystem } from "../memory/index.ts";
import type { TaskManager } from "./tasks/index.ts";
import type { ToolRegistry } from "../tools/registry.ts";
import type { ApprovalCallback } from "../tools/types.ts";
import { buildPrompt } from "./prompt.ts";
import { callClaude } from "./claude-cli.ts";
import { callAnthropicAPI } from "./anthropic-api.ts";
import { runChatLoop } from "./chat-loop.ts";
import { parseTaskIntents } from "./tasks/intents.ts";
import { decompose } from "./tasks/orchestrator.ts";

function timeAgo(dateStr?: string): string {
  if (!dateStr) return "unknown";
  const ms = Date.now() - new Date(dateStr).getTime();
  const mins = Math.floor(ms / 60000);
  if (mins < 1) return "just now";
  if (mins < 60) return `${mins}m ago`;
  const hours = Math.floor(mins / 60);
  if (hours < 24) return `${hours}h ago`;
  return `${Math.floor(hours / 24)}d ago`;
}

export interface IncomingMessage {
  type: "text" | "voice" | "photo" | "document";
  text: string; // Original text, transcription, or caption
  filePath?: string; // For images/documents (local temp path, legacy)
  fileBuffer?: Buffer; // Raw file data for vision / extraction
  fileUrl?: string; // Supabase Storage persistent URL
  mimeType?: string; // e.g. "image/jpeg", "application/pdf"
  originalFilename?: string; // Original filename from Telegram
  userId?: string; // Telegram user ID (for multi-user)
  metadata?: Record<string, unknown>;
}

export interface AgentResponse {
  text: string;
  taskIds: string[]; // IDs of background tasks spawned by this message
  images: string[]; // File paths of images generated by MCP tools
}

export async function handleMessage(
  message: IncomingMessage,
  config: Config,
  memory: MemorySystem,
  profile: string,
  taskManager?: TaskManager | null,
  registry?: ToolRegistry | null,
  requestApproval?: ApprovalCallback,
  agentTypeNames?: string[]
): Promise<AgentResponse> {
  const isPhone = message.metadata?.channel === "phone";

  // Save the user's message
  await memory.saveMessage("user", message.text, message.metadata);

  // For phone: Telnyx provides the full conversation history in each request,
  // so we use that directly instead of relying on semantic search (which has
  // embedding lag that makes it useless for rapid voice turns).
  // We still fetch facts/goals since those are pre-computed.
  const conversationHistory = (message.metadata?.conversationHistory as Array<{ role: string; content: string }>) || undefined;

  // Gather context in parallel — cheap Supabase queries only.
  // Semantic search is available via search_memory tool (LLM calls it when needed).
  const contextPromises: [Promise<string>, Promise<string>, Promise<string>, Promise<string>] = [
    memory.getMemoryContext(message.userId),
    taskManager
      ? taskManager.getActiveTasks(message.userId).then((tasks) => {
          if (!tasks.length) return "";
          return (
            "ACTIVE TASKS:\n" +
            tasks
              .map((t) => `- [${t.id.substring(0, 8)}] ${t.status}: ${t.description}`)
              .join("\n")
          );
        })
      : Promise.resolve(""),
    taskManager
      ? taskManager.getRecentCompletions(message.userId).then((tasks) => {
          if (!tasks.length) return "";
          return (
            "RECENTLY COMPLETED TASKS:\n" +
            tasks
              .map((t) => {
                const preview = t.result ? t.result.substring(0, 500) : "(no result)";
                const ago = timeAgo(t.completedAt);
                return `- [${t.id.substring(0, 8)}] ${t.status} (${ago}): ${t.description}\n  Result: ${preview}`;
              })
              .join("\n")
          );
        })
      : Promise.resolve(""),
    // Recent message history — always fetch; phone gets fewer (cross-channel context)
    memory.getRecentMessages(isPhone ? 20 : 50),
  ];

  const [memoryContext, taskContext, completedTaskContext, rawRecentMessages] = await Promise.all(contextPromises);

  // Relabel recent messages for phone so Claude knows they're cross-channel
  const recentMessages = isPhone && rawRecentMessages
    ? rawRecentMessages.replace("RECENT CONVERSATION:", "RECENT ACTIVITY (Telegram & other channels):")
    : rawRecentMessages;

  // Build the prompt text and optional image content for vision
  let promptText = message.text;
  let imageBase64: { data: string; mediaType: string } | undefined;

  if (message.type === "voice") {
    promptText = `[Voice message transcribed]: ${message.text}`;
  } else if (message.type === "photo") {
    // Image sent as a vision content block when buffer is available
    if (message.fileBuffer && message.mimeType) {
      imageBase64 = {
        data: message.fileBuffer.toString("base64"),
        mediaType: message.mimeType,
      };
    }
    promptText = message.text || "Analyze this image.";
  } else if (message.type === "document") {
    // Extracted text is already in message.text from the bot handler
    promptText = message.text;
  }

  // Collect available tool names for prompt context
  const availableTools = registry ? registry.getChatTools().map((t) => t.definition.name) : [];

  const channel = (message.metadata?.channel as "telegram" | "phone") || "telegram";

  const prompt = buildPrompt(promptText, {
    profile,
    userConfig: config.user,
    memoryContext,
    recentMessages,
    taskContext,
    completedTaskContext,
    availableTools,
    channel,
    conversationHistory,
    agentTypeNames,
  });

  // Call Claude via the configured backend
  // For phone: use a faster model and lower max_tokens for reduced latency
  const effectiveConfig = isPhone && config.anthropic
    ? {
        ...config.anthropic,
        model: process.env.PHONE_MODEL || "claude-haiku-4-5-20251001",
        maxTokens: Math.min(config.anthropic.maxTokens, 1024),
      }
    : config.anthropic;

  let rawResponse: string;
  let images: string[] = [];
  if (config.agentBackend === "api" && effectiveConfig) {
    if (registry && registry.getChatTools().length > 0) {
      // Chat loop with tool use
      const result = await runChatLoop({
        systemPrompt: prompt.system,
        userMessage: prompt.user,
        config: effectiveConfig,
        registry,
        requestApproval,
        imageBase64,
      });
      rawResponse = result.text;
      images = result.images;
    } else {
      // Simple API call (no tools)
      rawResponse = await callAnthropicAPI(
        prompt.system,
        prompt.user,
        effectiveConfig,
        imageBase64
      );
    }
  } else {
    rawResponse = await callClaude(
      prompt.system + "\n\nUser: " + prompt.user,
      config.claude
    );
  }

  // Parse memory intents and clean the response
  const cleanResponse = await memory.processIntents(
    rawResponse,
    message.userId
  );

  // Parse task intents and execute them
  const { clean: finalResponse, intents: taskIntents } =
    parseTaskIntents(cleanResponse);

  const taskIds: string[] = [];
  for (const intent of taskIntents) {
    if (intent.type === "create" && intent.description && taskManager) {
      const taskId = await taskManager.createAndRunTask(
        intent.description,
        message.userId,
        intent.agentType
      );
      if (taskId && !taskId.startsWith("Failed") && !taskId.startsWith("Tasks require")) {
        taskIds.push(taskId);
      }
    }
    if (intent.type === "chain" && intent.chainSteps?.length && taskManager) {
      const chainId = await taskManager.createTaskChain(intent.chainSteps, message.userId);
      if (chainId) taskIds.push(chainId);
    }
    if (intent.type === "flow" && intent.description && taskManager && config.anthropic) {
      try {
        const nodes = await decompose(
          intent.description,
          agentTypeNames || [],
          config.anthropic
        );
        const flowIds = await taskManager.createTaskFlow(nodes, message.userId);
        taskIds.push(...flowIds);
      } catch (err: any) {
        console.error("TASKFLOW decomposition failed:", err.message);
        // Fallback: create as a single default task
        const taskId = await taskManager.createAndRunTask(intent.description, message.userId);
        if (taskId && !taskId.startsWith("Failed") && !taskId.startsWith("Tasks require")) {
          taskIds.push(taskId);
        }
      }
    }
    if (intent.type === "cancel" && intent.taskId && taskManager) {
      await taskManager.cancelTask(intent.taskId);
    }
  }

  // Save the assistant's response (preserve channel from original message)
  await memory.saveMessage("assistant", finalResponse, message.metadata);

  return { text: finalResponse, taskIds, images };
}
