/**
 * MCP Client Manager
 *
 * Manages connections to MCP servers via stdio transport.
 * Each server runs as a child process; the manager handles
 * connect, tool listing, tool calls, and cleanup.
 */

import { Client } from "@modelcontextprotocol/sdk/client/index.js";
import { StdioClientTransport } from "@modelcontextprotocol/sdk/client/stdio.js";
import { writeFileSync, mkdirSync } from "fs";
import { join } from "path";
import { tmpdir } from "os";
import type { FileStore } from "../../utils/file-store.ts";

export interface MCPServerConfig {
  /** Unique name for this server (used as tool namespace) */
  name: string;
  /** Command to spawn the server */
  command: string;
  /** Arguments for the command */
  args?: string[];
  /** Environment variables for the server process */
  env?: Record<string, string>;
  /** Working directory for the server process */
  cwd?: string;
  /** Approval policy for all tools from this server */
  approvalPolicy?: "never" | "always" | "destructive";
  /** Where tools from this server can be used (default: "both") */
  scope?: "chat" | "background" | "both";
}

export interface MCPToolDefinition {
  name: string;
  description?: string;
  inputSchema: Record<string, unknown>;
}

interface ConnectedServer {
  config: MCPServerConfig;
  client: Client;
  transport: StdioClientTransport;
  tools: MCPToolDefinition[];
}

export class MCPClientManager {
  private servers = new Map<string, ConnectedServer>();
  /** Images generated by MCP tools during the current chat turn */
  private _pendingImages: string[] = [];
  /** Optional cloud file store for auto-uploading MCP outputs */
  private fileStore: FileStore | null = null;

  /** Inject a FileStore for auto-uploading MCP file outputs to cloud storage */
  setFileStore(store: FileStore): void {
    this.fileStore = store;
  }

  /**
   * Connect to an MCP server and discover its tools.
   */
  async connect(serverConfig: MCPServerConfig): Promise<MCPToolDefinition[]> {
    if (this.servers.has(serverConfig.name)) {
      console.log(`MCP server "${serverConfig.name}" already connected`);
      return this.servers.get(serverConfig.name)!.tools;
    }

    const client = new Client(
      { name: "bright", version: "1.0.0" },
      { capabilities: {} }
    );

    // Merge current process env with server-specific env
    const env = {
      ...process.env,
      ...(serverConfig.env || {}),
    } as Record<string, string>;

    const transport = new StdioClientTransport({
      command: serverConfig.command,
      args: serverConfig.args,
      env,
      cwd: serverConfig.cwd,
      stderr: "pipe",
    });

    try {
      await client.connect(transport);
      console.log(`MCP: connected to "${serverConfig.name}"`);
    } catch (err: unknown) {
      const msg = err instanceof Error ? err.message : String(err);
      console.error(`MCP: failed to connect to "${serverConfig.name}": ${msg}`);
      throw err;
    }

    // Discover tools
    let tools: MCPToolDefinition[] = [];
    try {
      const result = await client.listTools();
      tools = result.tools.map((t) => ({
        name: t.name,
        description: t.description,
        inputSchema: t.inputSchema as Record<string, unknown>,
      }));
      console.log(
        `MCP: "${serverConfig.name}" provides ${tools.length} tool(s): ${tools.map((t) => t.name).join(", ")}`
      );
    } catch (err: unknown) {
      const msg = err instanceof Error ? err.message : String(err);
      console.error(`MCP: failed to list tools from "${serverConfig.name}": ${msg}`);
    }

    this.servers.set(serverConfig.name, {
      config: serverConfig,
      client,
      transport,
      tools,
    });

    return tools;
  }

  /**
   * Call a tool on a specific server.
   * Returns the text content of the result.
   * Image content blocks are saved to temp files and queued as pending images.
   */
  async callTool(
    serverName: string,
    toolName: string,
    args: Record<string, unknown>
  ): Promise<string> {
    const server = this.servers.get(serverName);
    if (!server) {
      throw new Error(`MCP server "${serverName}" not connected`);
    }

    const result = await server.client.callTool({
      name: toolName,
      arguments: args,
    });

    if (result.isError) {
      const errorText = result.content
        ?.filter((c): c is { type: "text"; text: string } => c.type === "text")
        .map((c) => c.text)
        .join("\n");
      throw new Error(errorText || "MCP tool returned an error");
    }

    const textParts: string[] = [];

    for (const block of result.content || []) {
      if (block.type === "text") {
        textParts.push((block as { type: "text"; text: string }).text);

        // Detect file paths in text output (e.g., nanobanana "saved to:" messages)
        const pathMatch = (block as { text: string }).text.match(
          /saved to:\s*(.+\.(png|jpg|jpeg|webp|gif|mp3|wav|ogg|m4a|mp4|pdf|csv))/i
        );
        if (pathMatch) {
          const savedPath = pathMatch[1].trim();
          this._pendingImages.push(savedPath);

          // Auto-upload to cloud storage if available
          if (this.fileStore) {
            const url = await this.fileStore.upload(savedPath);
            if (url) textParts.push(`[URL: ${url}]`);
          }
        }
      } else if (block.type === "image") {
        // Save base64 image to temp file
        const imgBlock = block as { type: "image"; data: string; mimeType?: string };
        const ext = imgBlock.mimeType?.includes("jpeg") || imgBlock.mimeType?.includes("jpg") ? "jpg" : "png";
        const imgDir = join(tmpdir(), "bright-images");
        mkdirSync(imgDir, { recursive: true });
        const imgPath = join(imgDir, `mcp_${Date.now()}.${ext}`);
        writeFileSync(imgPath, Buffer.from(imgBlock.data, "base64"));
        this._pendingImages.push(imgPath);
        textParts.push(`[Image saved to: ${imgPath}]`);

        // Auto-upload to cloud storage if available
        if (this.fileStore) {
          const publicUrl = await this.fileStore.upload(imgPath);
          if (publicUrl) {
            textParts.push(`[URL: ${publicUrl}]`);
          }
        }
      }
    }

    return textParts.join("\n") || "(no output)";
  }

  /** Get and clear pending images from recent tool calls */
  takePendingImages(): string[] {
    const images = [...this._pendingImages];
    this._pendingImages = [];
    return images;
  }

  /**
   * Get all connected server names.
   */
  getServerNames(): string[] {
    return Array.from(this.servers.keys());
  }

  /**
   * Get tools for a specific server.
   */
  getServerTools(serverName: string): MCPToolDefinition[] {
    return this.servers.get(serverName)?.tools || [];
  }

  /**
   * Disconnect a specific server.
   */
  async disconnect(serverName: string): Promise<void> {
    const server = this.servers.get(serverName);
    if (!server) return;

    try {
      await server.transport.close();
      console.log(`MCP: disconnected from "${serverName}"`);
    } catch (err: unknown) {
      const msg = err instanceof Error ? err.message : String(err);
      console.error(`MCP: error disconnecting "${serverName}": ${msg}`);
    }

    this.servers.delete(serverName);
  }

  /**
   * Disconnect all servers. Call this on shutdown.
   */
  async disconnectAll(): Promise<void> {
    const names = Array.from(this.servers.keys());
    await Promise.allSettled(names.map((name) => this.disconnect(name)));
  }
}
