/**
 * Tool Registry
 *
 * Central registry for all tools. Provides filtered views by scope
 * and generates Anthropic tool definition arrays for API calls.
 */

import type Anthropic from "@anthropic-ai/sdk";
import type { ChatTool } from "./types.ts";
import type { MCPClientManager } from "./mcp/client.ts";

export class ToolRegistry {
  private tools = new Map<string, ChatTool>();
  private mcpManager?: MCPClientManager;

  register(tool: ChatTool): void {
    this.tools.set(tool.definition.name, tool);
  }

  registerAll(tools: ChatTool[]): void {
    for (const tool of tools) this.register(tool);
  }

  unregister(name: string): void {
    this.tools.delete(name);
  }

  get(name: string): ChatTool | undefined {
    return this.tools.get(name);
  }

  /** Tools available for the main chat loop */
  getChatTools(): ChatTool[] {
    return [...this.tools.values()].filter(
      (t) => t.scope === "chat" || t.scope === "both"
    );
  }

  /** Tools available for background tasks */
  getBackgroundTools(): ChatTool[] {
    return [...this.tools.values()].filter(
      (t) => t.scope === "background" || t.scope === "both"
    );
  }

  /** Anthropic tool definitions for chat API calls */
  getChatToolDefinitions(): Anthropic.Messages.Tool[] {
    return this.getChatTools().map((t) => t.definition);
  }

  /** All registered tool names */
  listNames(): string[] {
    return [...this.tools.keys()];
  }

  get size(): number {
    return this.tools.size;
  }

  /** Set the MCP manager so we can collect generated images */
  setMCPManager(manager: MCPClientManager): void {
    this.mcpManager = manager;
  }

  /** Get and clear any images generated by MCP tools during recent calls */
  takePendingImages(): string[] {
    return this.mcpManager?.takePendingImages() || [];
  }
}
